name: moddable
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get install -y gcc git wget make libncurses-dev flex bison gperf
        sudo apt-get install -y libgtk-3-dev
        mkdir ~/Projects
        cd ~/Projects
        git clone https://github.com/Moddable-OpenSource/moddable
        MODDABLE=~/Projects/moddable
        export MODDABLE
        cd $MODDABLE/build/makefiles/lin
        make
        export PATH=$PATH:$MODDABLE/build/bin/lin/release
        cd $MODDABLE/build/makefiles/lin
        make install
        #xsbug
        #cd $MODDABLE/examples/helloworld
        cd ~/work/node-red-mcu/node-red-mcu
        mcconfig -d -m -p lin
